alias(
    name = "true",
    actual = "//constraints/is_systemcore:false",
    visibility = ["//visibility:public"],
)

config_setting(
    name = "trixie64",
    constraint_values = [
        "@platforms//os:linux",
        "@platforms//cpu:arm64",
        ":true",
    ],
    visibility = ["//visibility:public"],
)

config_setting(
    name = "trixie64_debug",
    constraint_values = [
        "@platforms//os:linux",
        "@platforms//cpu:arm64",
        ":true",
    ],
    values = {
        "compilation_mode": "dbg",
    },
    visibility = ["//visibility:public"],
)
